name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
        type: string
  push:
    tags: [ '*.*.*' ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: aipriceaction-proxy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,prefix={{branch}}-,format=short

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          GIT_COMMIT=${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test built image
      if: github.event_name != 'pull_request'
      run: |
        # Start container in background
        docker run -d --name test-container \
          -e PRIMARY_TOKEN=test-token \
          -e SECONDARY_TOKEN=test-token2 \
          -e INTERNAL_PEER_URLS= \
          -e PORT=8888 \
          -e RUST_LOG=info \
          -p 8888:8888 \
          ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

        # Wait for server to start
        sleep 5

        # Test health endpoint
        curl -f http://localhost:8888/health || (docker logs test-container && exit 1)

        # Check route registration in logs
        docker logs test-container 2>&1 | grep "Registering routes" || echo "Warning: Route registration log not found"
        docker logs test-container 2>&1 | grep "GET  /raw" || echo "Warning: /raw route not found in logs"

        # Stop and remove container
        docker stop test-container
        docker rm test-container